package code

const (
	//ActionSuccess 成功
	ActionSuccess = 20000
	// ActionArgsError 参数错误
	ActionArgsError = 20001
	// ActionDbError 数据库错误
	ActionDbError = 20002
	// ActionCreateUserError 创建用户错误
	ActionCreateUserError = 20003
	// ActionUserNotFound 用户不存在
	ActionUserNotFound = 20004
	// ActionPropNotExists 道具不存在
	ActionPropNotExists = 20005
	// ActionPropNotEnough 道具不足
	ActionPropNotEnough = 20006
	// ActionGoldNotEnough 金币不足
	ActionGoldNotEnough = 20007
	// ActionUnknownIllustrationID 未知的图集ID
	ActionUnknownIllustrationID = 20008
	// ActionNotGetIllustrationAward 不能获取图集奖励
	ActionNotGetIllustrationAward = 20009
	// ActionGetWeixinOpenIDError  获取微信ID错误
	ActionGetWeixinOpenIDError = 20010
	// ActionOpenIDIsNotEmpty  OpenID是不能为空的
	ActionOpenIDIsNotEmpty = 20011
	// ActionNotAccOfflineNum 没有离线能量可以领取
	ActionNotAccOfflineNum = 20012
	// ActionNotLegitimateConstellID 非合法的星座ID
	ActionNotLegitimateConstellID = 20013
	// ActionTimeNotEnough 时间不足
	ActionTimeNotEnough = 20014
	// ActionUnknownConstellationBuffType 未知的buff类型
	ActionUnknownConstellationBuffType = 20015
	// ActionNotLegitimateStarNum 未知的StarNum
	ActionNotLegitimateStarNum = 20016
	// ActionStarAlreadyStartUp 星星已经被点亮了
	ActionStarAlreadyStartUp = 20017
	// ActionPowerNotEnough 能量不够哇
	ActionPowerNotEnough = 20018
	// ActionNotRebirth 没有通关, 不能重生
	ActionNotRebirth = 20019
	// ActionNotChoiceConstellationBuff 不能选择buff 应为重生次数不为1
	ActionNotChoiceConstellationBuff = 20020
	// ActionUnkonownAchievementTypeOrOrder 未知的成就类型或者序列
	ActionUnkonownAchievementTypeOrOrder = 20021
	// ActionAchievementNotExists  成就不存在, 意思就是这个成就还没有满足
	ActionAchievementNotExists = 20022
	// ActionAlreadyHaveSpeedPlayer 该玩家已经结成了速配
	ActionAlreadyHaveSpeedPlayer = 20023
	// ActionUnknownMessageID 未知的消息ID
	ActionUnknownMessageID = 20024
	// ActionBeReplyMessageNotSpeedMsg 被回复的消息,不是速配消息
	ActionBeReplyMessageNotSpeedMsg = 20025
	// ActionUnknownConstellationID 未知的星座ID
	ActionUnknownConstellationID = 20026
	// ActionConstellationTagRepeated 星座标签重复
	ActionConstellationTagRepeated = 20027
	// ActionContentLegitimate 内容违法
	ActionContentLegitimate = 20028
	// ActionConstellationTagNotIsExists 星座标签不存在
	ActionConstellationTagNotIsExists = 20029
	// ActionUnknownWishingID 未知的许愿ID
	ActionUnknownWishingID = 20030
	// ActionNotFoundRank 没有找到该排名
	ActionNotFoundRank = 20031
	// ActionNotRepeatedClick 不能重复点击
	ActionNotRepeatedClick = 20032
	// ActionUnknownPeroperty 未知的属性ID
	ActionUnknownPeroperty = 30033
	// ActionUnknownBuffStarNum 未知的buff星星
	ActionUnknownBuffStarNum = 30034

	// ActionShareCountLimit 分享次数被限制
	ActionShareCountLimit = 30035
	// ActionCofigureErr 配置错误
	ActionCofigureErr = 30036
	// ActionUnknownShopID 未知的shopID
	ActionUnknownShopID = 30037
	// ActionBillIsNotEnough 金币不足
	ActionBillIsNotEnough = 30038
	// ActionNumIsNotEnough 数量不够
	ActionNumIsNotEnough = 30038
	// ActionStoveNotIdleOrExists 灶台被占用或者未开启或者不存在
	ActionStoveNotIdleOrExists = 30039
	// ActionFormalIDIsLegitimate 配方ID不合法
	ActionFormalIDIsLegitimate = 30040
	// ActionDoDishedFailed 做菜失败
	ActionDoDishedFailed = 30041
	// ActionFormalIsNotIdle 菜谱不空闲
	ActionFormalIsNotIdle = 30042
	// ActionOutStoveFailed 出灶台失败
	ActionOutStoveFailed = 30043
	// ActionNotGetAward 不能获取奖励
	ActionNotGetAward = 30044
	// ActionUnknownID 未知的ID
	ActionUnknownID = 30045
	// ActionStoveIsIdle 炉灶是空闲的
	ActionStoveIsIdle = 30046
)
